# Generated by Django 3.0.5 on 2021-02-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20210210_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name='Ширина'),
        ),
    ]
