# Generated by Django 3.0.5 on 2021-02-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20210211_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image_file',
            field=models.ImageField(blank=True, height_field='height', null=True, upload_to='images/', verbose_name='Файл', width_field='width'),
        ),
    ]
