# Generated by Django 3.0.5 on 2021-02-12 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_auto_20210212_2003'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Addimage',
        ),
    ]
