# Generated by Django 3.0.5 on 2021-02-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20210212_2026'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Ссылка')),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Файл')),
            ],
        ),
        migrations.DeleteModel(
            name='Addimage',
        ),
    ]
